# Generated by Django 4.1.7 on 2023-06-28 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpapp', '0003_alter_movimentacoesxp_data_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoxp',
            name='categoria',
            field=models.CharField(default='catxp', max_length=200),
        ),
        migrations.AlterField(
            model_name='movimentacoesxp',
            name='data_movimentacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 49, 8, 902280)),
        ),
    ]
