# Generated by Django 4.1.7 on 2024-02-26 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMovimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('cd_tipo', models.CharField(default=' ', max_length=20)),
                ('cd_jcot', models.TextField()),
                ('cotista', models.TextField()),
                ('vl_original', models.FloatField()),
                ('vl_liquido', models.FloatField()),
                ('vl_bruto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContaEfin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.FloatField()),
                ('debitos', models.FloatField()),
                ('principal', models.FloatField(default=0)),
                ('creditosmsmtitu', models.FloatField()),
                ('debitosmsmtitu', models.FloatField()),
                ('vlrultidia', models.FloatField()),
                ('fundoCnpj', models.CharField(max_length=14)),
                ('numconta', models.TextField(max_length=14)),
                ('data_final', models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 1, 35, 24384))),
            ],
        ),
        migrations.CreateModel(
            name='InvestidorEfin',
            fields=[
                ('nome', models.CharField(default='', max_length=256)),
                ('cpfcnpj', models.CharField(default='', max_length=14, primary_key=True, serialize=False)),
                ('endereco', models.TextField(default='', max_length=256)),
                ('pais', models.TextField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaOperacao', models.CharField(max_length=100)),
                ('notaAplicacao', models.CharField(max_length=100)),
                ('dsFormaLiquidacao', models.CharField(max_length=100)),
                ('tpLiquidacao', models.CharField(max_length=100)),
                ('dsContaLiquidacao', models.CharField(max_length=100)),
                ('qtdCotas', models.FloatField()),
                ('vlOriginal', models.FloatField()),
                ('vlOperacao', models.FloatField()),
                ('vlIR', models.FloatField()),
                ('vlPenaltyFee', models.FloatField()),
                ('vlReceitaSaqueCarencia', models.FloatField()),
                ('vlIOF', models.FloatField()),
                ('vlLiquido', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 1, 35, 42382))),
                ('cotista', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='ResgatesJcot',
            fields=[
                ('data_movimento', models.DateTimeField()),
                ('data_liquidacao', models.DateTimeField()),
                ('nota', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('cd_tipo', models.CharField(default=' ', max_length=20)),
                ('cd_cotista', models.CharField(default=' ', max_length=16)),
                ('cd_fundo', models.TextField()),
                ('vl_original', models.FloatField()),
                ('vl_liquido', models.FloatField()),
                ('vl_bruto', models.FloatField()),
            ],
        ),
    ]
