# Generated by Django 4.1.7 on 2024-02-23 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 9, 58, 15, 167915)),
        ),
        migrations.AlterField(
            model_name='movimentodetalhado',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 9, 58, 15, 169916)),
        ),
    ]
