# Generated by Django 4.1.7 on 2024-02-15 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidorefin',
            name='data_final',
        ),
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 18, 30, 13, 953644)),
        ),
    ]
