# Generated by Django 4.1.7 on 2024-02-19 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0002_remove_investidorefin_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaefin',
            name='principal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 37, 33, 610135)),
        ),
    ]
