# Generated by Django 4.1.7 on 2024-02-21 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0003_contaefin_principal_alter_contaefin_data_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 12, 51, 58, 411546)),
        ),
    ]
