# Generated by Django 4.1.7 on 2024-02-21 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0004_alter_contaefin_data_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResgatesJcot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField()),
                ('data_liquidacao', models.DateTimeField()),
                ('nota', models.CharField(default=' ', max_length=50)),
                ('cd_tipo', models.CharField(default=' ', max_length=20)),
                ('cd_cotista', models.CharField(default=' ', max_length=16)),
                ('cd_fundo', models.TextField()),
                ('vl_original', models.FloatField()),
                ('vl_liquido', models.FloatField()),
                ('vl_bruto', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 13, 43, 55, 272462)),
        ),
    ]
