# Generated by Django 4.1.7 on 2024-02-21 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_legais', '0008_alter_contaefin_data_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentodetalhado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resgatesjcot',
            name='id',
        ),
        migrations.AlterField(
            model_name='contaefin',
            name='data_final',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 19, 53, 5, 849711)),
        ),
        migrations.AlterField(
            model_name='movimentodetalhado',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 19, 53, 5, 858710)),
        ),
        migrations.AlterField(
            model_name='movimentodetalhado',
            name='notaOperacao',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resgatesjcot',
            name='nota',
            field=models.CharField(default=' ', max_length=50, primary_key=True, serialize=False),
        ),
    ]
