# Generated by Django 4.1.7 on 2023-06-28 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosXp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40)),
                ('filedate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FundoXP',
            fields=[
                ('o2id', models.BigIntegerField(default=0)),
                ('nome', models.CharField(max_length=200)),
                ('cd_jcot', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InvestidoresXp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO_CGC', models.CharField(default=0, max_length=15)),
                ('CD_CLIENTE', models.CharField(max_length=15)),
                ('NM_CLIENTE', models.CharField(max_length=200)),
                ('IC_FJ_PESSOA', models.CharField(default=0, max_length=2)),
                ('DATA', models.DateTimeField()),
                ('C_ORDEM', models.CharField(max_length=3)),
                ('tipo_cotista', models.IntegerField(default=0)),
                ('statusJcot', models.BooleanField()),
                ('status_cadastro_cotista', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacoesXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_investidor', models.CharField(max_length=200)),
                ('cd_fundo', models.CharField(max_length=15)),
                ('tipo_movimentacao', models.CharField(default='A', max_length=15)),
                ('data_movimentacao', models.DateTimeField(default=datetime.datetime(2023, 6, 28, 18, 16, 3, 664312))),
                ('valor', models.FloatField()),
                ('filename', models.CharField(max_length=200)),
                ('statusJcot', models.BooleanField(default=False)),
            ],
        ),
    ]
