# Generated by Django 4.1.7 on 2023-11-28 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpapp', '0008_fundoxp_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoesxp',
            name='data_movimentacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 20, 19, 51, 107543)),
        ),
    ]
