# Generated by Django 4.1.7 on 2024-01-05 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpapp', '0018_fundoxp_descricao_o2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoxp',
            name='tipo_fundo',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='movimentacoesxp',
            name='data_movimentacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 13, 4, 28, 45634)),
        ),
    ]
