# Generated by Django 4.1.7 on 2023-11-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiFator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('fator', models.FloatField()),
                ('selic', models.FloatField()),
            ],
        ),
    ]
