# Generated by Django 4.1.7 on 2023-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=250)),
                ('data', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
