# Generated by Django 4.1.7 on 2023-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0002_floatdiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_ot', models.CharField(max_length=10)),
                ('tipo_ativo', models.CharField(max_length=20)),
            ],
        ),
    ]
