# Generated by Django 4.1.7 on 2023-12-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0004_arquivodconciliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFilePus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=25)),
                ('issuePrice', models.FloatField()),
            ],
        ),
    ]
