# Generated by Django 4.1.7 on 2023-12-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0005_securefilepus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdot',
            name='tipo_ativo',
            field=models.CharField(max_length=200),
        ),
    ]
