# Generated by Django 4.1.7 on 2024-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0006_alter_cdot_tipo_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_ot', models.CharField(max_length=20)),
                ('periodicidade', models.CharField(choices=[('Mensal', 'Mensal'), ('Anual', 'Anual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], max_length=10)),
                ('valor_remuneracao', models.FloatField()),
                ('emissor', models.CharField(max_length=250)),
                ('emissor_cnpj', models.TextField(max_length=14)),
                ('resumo_contrato', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo_ativo', models.CharField(max_length=25)),
            ],
        ),
    ]
