# Generated by Django 4.1.7 on 2024-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqdados', '0008_alter_receitamensal_valor_remuneracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitamensal',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receitamensal',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
